Implemented pages
TrueEdOs/memedict pull request #2
Opened 2020-05-19 08:43 UTC by TrueEdOs

Created set of pages with production-ready design.

2020-05-19 16:31 UTC, gmltA commented
Link to deployment?

2020-05-19 17:34 UTC, TrueEdOs commented
Sorry, here https://czar-dictionary.web.app/

2020-05-19 20:02 UTC, TrueEdOs commented
> Link to deployment?

Sorry, here https://czar-dictionary.web.app/

2020-05-20 19:54 UTC, gmltA requested changes

2020-05-20 19:54 UTC, gmltA commented on login.html
> +                    <h1 class="center-header" id="login-helper">Nickname</h1>
```suggestion
                    <label class="center-header" id="login-helper" for="login-enter">Nickname</label >

```

2020-05-20 19:54 UTC, gmltA commented on assets/css/header.css
> +  margin-top: -0.5em;
Use `line-height` instead of negative margins.

2020-05-22 15:47 UTC, gmltA approved these changes

2020-05-23 07:42 UTC, merged